### ISSUE TITLE
Font name?

### ISSUE THREAD

**Issue by subnut** [FrenzyExists/aquarium-vim#12]
What is the name of the cursive/italic font?  
What is the name of the regular font?

![image](https://user-images.githubusercontent.com/56714626/147418578-6f357766-dff9-4235-bf64-b00da02c6db9.png)

**Comment by FrenzyExists** [comment]
Font is Operator Mono. You can find it on my [dotfiles](https://github.com/FrenzyExists/dotfiles/tree/mozarrella/.fonts/Operator-Mono)

**Comment by nayaabkhan** [comment]
Sorry, but isn't that font actually https://github.com/FrenzyExists/dotfiles/tree/master/fonts/Cartograph%20CF?
