### ISSUE TITLE
Neovim Aquarium Colorscheme Doesn't Work

### ISSUE THREAD

**Issue by BooleanCube** [FrenzyExists/aquarium-vim#13]
**Describe the bug**
It looks weird and not right.

**To Reproduce**
1. Download the plugin using packer.nvim
2. Type the command :colo aquarium into neovim

**Expected behavior**
It should look like what's in the README.md

**Screenshots**
![image](https://user-images.githubusercontent.com/47650058/147614583-9ea3d57c-c993-45b5-b9ad-c08c66e1d8df.png)

**OS (The operating system you're using):**
 Windows 10

**Neovim (Your neovim version):**
0.6.0

**Comment by CafeAuLait-CC** [comment]
**RESOLVED**
- I solved my problem by adding the following lines into the **NeoVim** config file (according to the answer [here](https://unix.stackexchange.com/a/612641)):
	
	```
	if has("termguicolors")
	  set termguicolors
	  if &t_8f == ''
	    " The first characters after the equals sign are literal escape characters.
	    set t_8f=[38;2;%lu;%lu;%lum
	    set t_8b=[48;2;%lu;%lu;%lum
	  endif
	endif
	```
The above code enables true color display in **Vim**/ **NeoVim**. Thus it fixs the problem as long as **True Color** is supported by the termianl. (`Terminal.app` on macOS doesn't support True Color.)


 **Below is the original comment**
*****
Hello,

I'm having the similiar problem. I installed the colorscheme on both **macOS** and **LInux** (Raspberry Pi OS) systems. None of them works correctly.

#### My Configuration
- macOS 12.0.1
    - Vim 8.2 (macOS)
    - NeoVim 0.6 (macOS)
- Raspberry Pi OS (Bullseye Oct. 31, 2021)
    - NeoVim 0.4.4 (Linux) 

#### Description

I installed Aquarium via `vim-plug`, tried on both systems with **Vim** and **Neovim**. I tested it with/ without other plugins installed (for example `rust.vim`), but it doesn't affect the results. None of the syntax highlighting is correct.

#### Terminal settings outside vim
On macOS, I configured **iTerm2** with the color profile provided in the `extra` folder, and set the `Terminal.app` using the same pallete. On Linux, I set the terminal pallete manully.

Here are some screenshots to show what they look like:

Linux **Neovim** version **0.4.4**, *Keyword* and *Functios* and other staff not highlighted
![nvim_4_4_linux](https://user-images.githubusercontent.com/8164219/147695910-fc3c79f4-41d5-494a-908f-a683a15b385c.png)

macOS **NeoVim** version **0.6**
![nvim_6_macOS](https://user-images.githubusercontent.com/8164219/147696310-1454b26e-97c7-42dc-8533-6f54ab79f1cd.png)

And **Vim** version **8.2** on macOS has the worst case, the foreground and background color for some words are inverted:
![vim_8_2__macOS](https://user-images.githubusercontent.com/8164219/147696384-1af7f7b8-96a5-4a0c-9e22-7d5c5639a384.png)

I tried to check the color settings via `:hi Keyword` or `hi Number`
And it will show: 
![hi_keyword](https://user-images.githubusercontent.com/8164219/147697120-19cefd96-e3b1-4a1a-942b-cd1855f016d4.png)

I guess that means the color settings is only for gui vim, and `ctermfg`, `ctermbg` are not set for most of the things like **Keyword** and **Number**

I'm new to vim plugins, so please let me know if I'm doing wrong, or I need to install other plugins to help the the syntax highlight and make it look the same as your screenshot in the `README.md`

**Comment by FrenzyExists** [comment]
Hi! Sorry for the really late response. I believe you don't have termgui colors enabled on your neovim configuration on windows. And yes, I haven't exactly set any `cterm` colors per se, some have, some don't. Reason is because I don't exactly use `cterm` at all (and because I actually suck at using the base 256 color system of `cterm`). Make sure you have termgui colors enabled on your configuration.

About the plugins, If you ever wanted that there was more colors on the syntax side, you can install tree-sitter. Make sure your neovim version is 5.0 or above tho.

Have this somewhere on your .vimrc

`set termguicolors`

That will enable gui colors and fix the issue

**Comment by BooleanCube** [comment]
it was just that, in lua all you have to do is `vim.opt.termguicolors = true` and that did the job for me. thx for the help!
