### ISSUE TITLE
Should I work on a VSCode port?

### ISSUE THREAD

**Issue by FrenzyExists** [FrenzyExists/aquarium-vim#14]
Lately I've been using more and more vscode than neovim for coding, I've been wondering if its a good idea to spend some time for a vscode port of the theme. Let me know your thoughts!

**Comment by bakageddy** [comment]
More ports, the merrier!

**Comment by FrenzyExists** [comment]
I'll work on the port after finals

**Comment by FrenzyExists** [comment]
# Update:

## Tomorrow, Vscode Theme, because I finally got my lazy ass to finish it
