### ISSUE TITLE
Hi, your status bar is very nice, what software and theme are you using?

### ISSUE THREAD

**Issue by yyy33** [FrenzyExists/aquarium-vim#17]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**OS (The operating system you're using):**
 - e.g. Linux/Windows/Mac

**Neovim (Your neovim version)
- e.g. 5.0

**Additional context**

**Comment by FrenzyExists** [comment]
Sup!

The bar is Polybar, you can check it on my dotfiles :+1:
